services:
  postgres:
    container_name: postgres_prod
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: redis
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis-cluster:
    container_name: redis_prod
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: